### ISSUE TITLE
Expand pre-commit

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-aa-cookiecutter#10]
We have pretty cool pre-commit set-up in [pa-aa-toolbox](https://github.com/OCHA-DAP/pa-aa-toolbox). 
So thought it might be nice to add all of that to the cookiecutter. 
@turnerm what would you say? If so, are you able to do that easily?

**Comment by turnerm** [comment]
This was intentional as I wanted to keep things relatively simple for the country repos. Since the code in these isn't used in other projects it's not so important that it's perfect. Plus some of the hooks in `aa-toolbox` are not relevant, such as those for `pip-tools` or a `yaml` linter. 

However, happy to add more if you have any specific ones in mind!

**Comment by Tinkaa** [comment]
Yes you are totally right. 

I was thinking of `mypy` and maybe a few additional flake8 dependencies such as `docstrings`. Do you think that would be helpful or too much?

**Comment by turnerm** [comment]
Aha wow how the turn tables :) Yeah if you find it would be helpful then go for it!

**Comment by Tinkaa** [comment]
I have been thinking about this, but in the end agree that it is too restricting in neatness of code, so gonna leave it as it is for now, until opinions change again.
